[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lucisqr"
authors = [{name = "Henrique Bucher", email = "henry@vitorian.com"}]
dynamic = ["version", "description"]
